name: Create New BaseImage docker
on:
  push:
    tags:
      - baseimage-*

jobs:
  build-base-image-push-docker:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - name: Checkout
      uses: actions/checkout@v2

    # get dockerhub access token secret from vault
    - name: Get DockerHub Access Token
      id: vault
      env:
        ROLE_ID: ${{ secrets.ROLE_ID }}
        SECRET_ID: ${{ secrets.SECRET_ID }}
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      run: |
        # get vault token using role-id and secret-id
        VAULT_TOKEN=$(curl \
            --request POST \
            --data "{\"role_id\":\"${ROLE_ID}\",\"secret_id\":\"${SECRET_ID}\"}" \
            ${VAULT_ADDR}/v1/auth/approle/login | jq -r .auth.client_token)
        if [ -z "${VAULT_TOKEN}" ] ; then
           echo "Vault authentication failed!"
           exit 1
        fi
        echo ::add-mask::${VAULT_TOKEN}
        echo ::set-env name=VAULT_TOKEN::${VAULT_TOKEN}

        # use vault token to read secret - dockerhub access token
        DOCKERHUB_PASSWORD=$(curl --silent -H "X-Vault-Token: ${VAULT_TOKEN}" -X GET \
             ${VAULT_ADDR}/v1/secret/dsde/gotc/dev/ci/dsdejenkins-dockerhub \
             | jq .data.accesstoken | tr -d '"' )
        echo ::add-mask::${DOCKERHUB_PASSWORD}
        echo ::set-env name=DOCKERHUB_PASSWORD::${DOCKERHUB_PASSWORD}
        if [ -z "${DOCKERHUB_PASSWORD}" ] ; then
           echo "Retrieval of Dockerhub access token failed"
           exit 1
        fi

        # use vault token to read secret - dockerhub username
        DOCKERHUB_USERNAME=$(curl --silent -H "X-Vault-Token: ${VAULT_TOKEN}" -X GET \
             ${VAULT_ADDR}/v1/secret/dsde/gotc/dev/ci/dsdejenkins-dockerhub \
             | jq .data.username | tr -d '"')
        echo ::add-mask::${DOCKERHUB_USERNAME}
        echo ::set-env name=DOCKERHUB_USERNAME::${DOCKERHUB_USERNAME}
        if [ -z "${DOCKERHUB_USERNAME}" ] ; then
           echo "Retrieval of Dockerhub username failed"
           exit 1
        fi

    # get tag  name
    - name: Get tag name
      id: tagName
      run: |
        # get tag name
        echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
        # get derived docker tag name
        echo ::set-output name=DOCKER_TAG::${TAG_NAME/baseimage-/}

    # docker build push if baseimage- tag provided
    - name: Build and Push Docker Images
      id: docker-build
      if: ${{ steps.tagName.outputs.DOCKER_TAG }} != ${{ steps.tagName.outputs.TAG_NAME }}
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}
        repository: broadinstitute/github-action-template-render
        add_git_labels: true
        dockerfile: base-image/Dockerfile
        path: base-image
        tag_with_sha: false
        tags: ${{ steps.tagName.outputs.DOCKER_TAG }}
        push: true




